title: "Scène"
email: info@example.com
description: "料理のために用意された、静かな一夜。"

# 【重要】リポジトリ名を設定します（先頭にスラッシュが必要）
# これがないとCSSや画像が読み込まれません
baseurl: ""

# 【重要】GitHub Pagesの基本ドメインを設定します
url: "https://eisukekodani-debug.github.io"

timezone: Asia/Tokyo

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 予約リンク
reservation_url: "https://www.jalan.net/yad353095/"

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "jp"
    values:
      lang: "jp"
  - scope:
      path: "en"
    values:
      lang: "en"
